import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
const inter = Inter({ subsets: ['latin'] })
import Sidebar from '@/components/Sidebar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#151515] text-white`}>
      <Navbar />
      <div className="flex min-h-screen px-10">
        <Sidebar />
        {children}
      </div>
        </body>
    </html>
  )
}

/* 
altura de la pagina: 5162.030px
 */